---
  - hosts: cloud_node
    become: true
    tasks:

    - name: update packages on Rocky nodes
      yum:
        name: '*'
        state: latest
      when: ansible_distribution in ['Rocky', 'RedHat']

    - name: update packes on Ubuntu nodes
      apt:
        name: '*'
        state: latest
      when: ansible_distribution in ['Ubuntu', 'Debian']
